### ISSUE TITLE
Newest master doesn't compile with GHC 9.2.1

### ISSUE THREAD

**Issue by Mikolaj** [VinylRecords/Vinyl#156]
~/r/Vinyl$ cabal build
...
[13 of 19] Compiling Data.Vinyl.Syntax ( Data/Vinyl/Syntax.hs, /home/mikolaj/r/Vinyl/dist-newstyle/build/x86_64-linux/ghc-9.2.1/vinyl-0.14.0/build/Data/Vinyl/Syntax.o, /home/mikolaj/r/Vinyl/dist-newstyle/build/x86_64-linux/ghc-9.2.1/vinyl-0.14.0/build/Data/Vinyl/Syntax.dyn_o )

Data/Vinyl/Syntax.hs:36:10: error:
    • Non type-variable argument
        in the constraint: Data.Vinyl.Lens.RecElem
                             record
                             (s ::: t)
                             (s ::: t')
                             ts
                             ts'
                             (Data.Vinyl.TypeLevel.RIndex (s ::: t) ts)
      (Use FlexibleContexts to permit this)
    • In the instance declaration for ‘IsLabel s (a' -> b')’
   |
36 | instance forall s t t' ts ts' f record a' b'.
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
~/r/Vinyl$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.1

**Comment by Mikolaj** [comment]
`FlexibleContexts` indeed suffices.

**Comment by Mikolaj** [comment]
\o/
