### ISSUE TITLE
ToARec class not exported

### ISSUE THREAD

**Issue by msakai** [VinylRecords/Vinyl#157]
`ToARec` class was introduced in 9375bbd434ea3f8c71793fe9965c967725b9bafc but is not exported. This prevents us from using the `toARec` function polymorphically.

E.g. [backdrop](https://github.com/mstksg/backprop) package has [the following code](https://github.com/mstksg/backprop/blob/e8962c2029476c7721c5f5488e8689737294ceee/src/Numeric/Backprop/Class.hs#L985-L993):

```haskell
-- | @since 0.2.6.3
instance (ReifyConstraint Backprop f rs, RMap rs, RApply rs, RecApplicative rs, NatToInt (RLength rs), RPureConstrained (IndexableField rs) rs)
      => Backprop (ARec f rs) where
    zero = toARec . zero . fromARec
    {-# INLINE zero #-}
    add xs ys = toARec $ add (fromARec xs) (fromARec ys)
    {-# INLINE add #-}
    one  = toARec . zero . fromARec
    {-# INLINE one #-}
```

If I compile the code with the current master of the `vinyl` (79dcb5911e6da07151d6e68d470a0dadb73a3ceb), it results in the following error:

```
.../backprop/src/Numeric/Backprop/Class.hs:988:12: error:
    • Could not deduce (Data.Vinyl.ARec.Internal.ToARec rs)
        arising from a use of ‘toARec’
      from the context: (ReifyConstraint Backprop f rs, RMap rs,
                         RApply rs, RecApplicative rs, NatToInt (RLength rs),
                         RPureConstrained (IndexableField rs) rs)
        bound by the instance declaration
        at src/Numeric/Backprop/Class.hs:(986,10)-(987,29)
    • In the first argument of ‘(.)’, namely ‘toARec’
      In the expression: toARec . zero . fromARec
      In an equation for ‘zero’: zero = toARec . zero . fromARec
    |
988 |     zero = toARec . zero . fromARec
    |            ^^^^^^
```

It is necessary to add `ToARec rs` to the class context, but it is impossible because the `ToARec` class is not exported.

**Comment by acowley** [comment]
@Philonous Any objection to exporting the class to support this use case?

**Comment by Philonous** [comment]
No, I think the only reason I didn't export it was not to bloat up the API.

**Comment by Mikolaj** [comment]
It seems this wasn't fixed in 0.14.1, right? I'm still having the error compiling backprop...

**Comment by acowley** [comment]
Sorry I lost track of getting this in, and thank you for the patient reminder!

**Comment by Mikolaj** [comment]
Thank you!
